### ISSUE TITLE
Promises in resolves

### ISSUE THREAD

**Issue by omegascorp** [owljsorg/owl.js#12]
For now result of resolve in owl.Router is Boolean. We need to change it to Promise to support ajax requests in resolves. But it also should still support Boolean return values. For now it keeps execution sequence but we can use Promise.all to do all calls in parallel․

**Comment by omegascorp** [comment]
@colshacol that task is not so interesting, but you can have a look on this one.

**Comment by dltmd6262** [comment]
Is this repo still maintained? I'm a new comer and I would love to make a PR :]

**Comment by omegascorp** [comment]
Yeah, you are welcome :)

**Comment by dltmd6262** [comment]
Alright! This is my first time so let follow up on the code and ask some questions here :]

**Comment by omegascorp** [comment]
Good :)

**Comment by dltmd6262** [comment]
Can you look at my first PR and tell me what you think?? :]
